conventional-changelog/standard-version

- .gitignore
- .travis.yml
- README.md
- index.js
- package.json
- test.js
* adds a test-suite, inspired by the integration tests in `standard-changelog`.
* adds support for `Node 0.10`.
* adds a header, _marketing for the win_
> feat(tests): adding a test suite

- README.md
- index.js
- package.json
- test.js
* based on a conversation with @ceejbot, I've forked the `angular` commit standards and lifted the character-length restrictions. This might be a bit controversial, but this helps me get more buy-in from other folks at npm, Inc.
* I've introduced a style guide specifically for `standard-version`, since we might have more opinionated changes in the future.
> slight changes to conventions, to help get more buy-in from npm peers

- README.md
- package.json
Adds support for GitHub username and GitHub issue URL parsing. fixes #13.
> feat: adds support for GitHub links (see #13), great idea @bcoe!

- index.js
we were appending too many `\n` characters, which causes some text editors to truncate content when they first open the CHANGELOG.
> fix: we had too many \n characters

- README.md
- package.json
Replaces #4.
- Slight tweaks to general description with updated link for conventional-changelog "recommended workflow"
- Clarify "checkout master" to include pull
- Clarify installation options (run script vs global bin) with benefits of each
- Add Usage section, moving initial changelog generation to First Release
- Add FAQ section addressing questions answered in #22 and #24
> docs(README): add faq and more details on installation/usage

- index.js
- test.js
Fixes #19. (Sorry @Conaclos I didn't realize the problem until today.)
We are formatting the commit message such that e.g.
`chore(release): %s` → `chore(release): 1.0.0`.
But I failed to notice we were **not** formatting the message for the annotated tag, so [as you can see](https://github.com/conventional-changelog/standard-version/releases/tag/v2.1.2) it stays as `chore(release): %s`.
Whoops!
This adds a test to verify the messages for the commit and for the tag, and fixes the issue.
> fix: format the annotated tag message

- index.js
- package.json
* pinned shelljs to a version that works with nyc, [filed a bug](https://github.com/shelljs/shelljs/issues/438) regarding this.
* upgraded other dependencies.
* switched us back to angular changelog (fixes #27).
> fix: upgrade, switch, pin dependencies

- index.js
- test.js
Builds on top of (and replaces) #18, with the following additions:
- Sign the commit as well as the tag
- Change the CLI option to `--sign` (instead of `--sign-tag`) and update the description
- Add a test that verifies GPG signing was attempted by git (and failed from lack of key)
> feat: add --sign flag to sign git commit and tag

- test.js
Mocks git (for a subset of tests) in order to better test:
- `--sign` attempts to sign the commit **and** tag
- exits with error if git commit fails
- exits with error if git tag fails
This improves code/line coverage from 91.57 to 95.18 percent.
Still need a way to induce/mock error scenarios for `conventionalRecommendedBump` and `conventionalChangelog`.
> test: mock git for some tests to improve code coverage

- package.json
- test.js
https://github.com/stevemao/mock-git
The standalone module has a few improvements:
1. It is async
2. It uses temp folder for path which is better than `cwd`
3. It also handles some potential edge cases
> refactor(mockGit): modulization

- README.md
- index.js
- test.js
Thanks for the awesome tool! We use a git pre-commit hook to test our code before committing and it seems to prevent the last step of standard-version (git tag). This PR adds a --no-verify option to disable git hook verification.
> Add a --no-verify option to prevent git hooks from being verified

- index.js
- test.js
Windows cmd doesn't support separating commands with ';'. Fix by separating
the execution of the 'git add' and 'git commit' commands.
Fixes #49
> fix(commit): fix windows by separating add and commit exec

- test.js
Explicitly run the cli with 'node <index.js path>' to fix running tests on windows.
There seems to be a bug overwriting project package.json and CHANGELOG.md
on windows after failed tests.
Fixes #50
> test: explicitly run cli with node to fix tests on windows

- appveyor.yml
I added ci.appveyor.com to this project. Not much changed since #57, removed the `core.autocrlf = true` config. Is there any need for it really?
> chore: add appveyor ci configuration

- package.json
It still remains in the dependency tree, but apparently it's not used explicitly by `standard-version`. Let's drop from package.json. (Thanks to [`npm-check`](https://github.com/dylang/npm-check) for this one.)
> chore(deps): drop unused conventional-changelog-angular dep

- index.js
So it doesn't look like something that was already done.
Before:
After:
Just a minor change.
> fix(index.js): use blue figures.info for last checkpoint

- index.js
`pkg.path` defaults to the closest package.json (https://github.com/conventional-changelog/conventional-changelog-core#path), which is the same as `npm-version`.
`outputUnreleased` does not do anything to this module.
> feat(changelogStream): use more default opts

- README.md
> docs(readme): Add section for signing commits and tags

- index.js
- test.js
For #91, this would stop `standard-version` from failing fast when `git` or hooks or something prints to `stderr`, but prints it out. Added test case it for as well. Also, errors are now printed to `stderr/console.error` instead of `stdout/console.log`.
/CC @nexdrew @duclet @e-cloud @stevemao @bcoe
> Don't fail on stderr output, but print the output to stderr

- .travis.yml
- README.md
- appveyor.yml
- cli.js
- defaults.json
- index.js
- package.json
- test.js
This might be a bit much, but actually nice in the long run. So the only parts that weren't being tested previously were `conventionalChangelog` and `conventionalRecommendedBump` error handling. The problem with handling them was that the `cli` was being called with shell execution, so mocking was nigh impossible. As a result, I did some restructuring:
* Separated the `cli` into `cli.js`
* `standard-version` actual logic in `index.js` with `module.exports` being a function
* This allows `standard-version` to be used by other tools, tests etc.
* Usage: `require('standard-version')(opts, callback)`
* `opts` is an object with `cli` options in camelcase, e.g. `{firstRelease: true}`
* `callback` will be called with possible error when `standard-version` is done (see `cli.js`)
* Separated …
> Restructuring for 100% test coverage

- README.md
Resolves #96.
@Tapppi @bcoe please take a look :)
> docs: Document commit-all flag with example

- test.js
Simply changed the assertion regex of the "commits all staged files" unit test to support a wording change made to git status in git v2.9.1 from _"working directory"_ to _"working tree"_
See:
https://github.com/git/git/commit/2a0e6cdedab306eccbd297c051035c13d0266343
Fixes #138
> fix: support a wording change made to git status in git v2.9.1

- index.js
- test.js
By passing `merges: null` to the conventional-changelog function the default "--no-merges" git CLI argument is removed, and therefore both normal and merge commits are returned from the log for processing.
Note that setting it to `true` would have changed "--no-merges" to "--merges", causing _only_ merges to be retrieved from the log.
Fixes #137
> fix: include merge commits in the changelog

- command.js
- defaults.json
- index.js
At Aurelia we don't use any tag prefixes, our tags are just `1.0`, thus we couldn't use `standard-version` as is. Right now `standard-version` has a hardcoded `v` prefix for all the git tags for releases, i.e. `v1.0`, `v1.1`. This change makes it configurable so you can have no prefix or a custom prefix if you wish. I left the default `v` prefix, so this is a non-breaking change.
> feat: make tagPrefix configurable

- README.md
- index.js
- test.js
working from @lexich's foundation, this pull adds support for bumping version # in multiple config files in a generic way.
> feat: add support for bumping version # in bower.json

- index.js
- test.js
Hi, I use your module since a few weeks, and as I missed this little feature, here it is.
By the way, I fixed the bower test since it didn't check the `bower.json` file. :smile: 
Thank for your great work.
Aurélien
> feat: add support for `npm-shrinkwrap.json`

- README.md
- command.js
- defaults.json
- index.js
- lib/checkpoint.js
- lib/print-error.js
- lib/run-exec.js
- lib/run-lifecycle-hook.js
- lib/run-lifecycle-script.js
- lib/write-file.js
- test.js
running standard-version with the flag --dry-run allows you to see what commands would be run, without committing to git or updating files.
@azachar I've implemented your suggestion for dry-run mode here 👍
> feat: add dry-run mode

- README.md
- command.js
- defaults.json
- index.js
- lib/checkpoint.js
- lib/format-commit-message.js
- lib/lifecycles/bump.js
- lib/lifecycles/changelog.js
- lib/lifecycles/commit.js
- lib/lifecycles/tag.js
- lib/run-lifecycle-script.js
- test.js
this fairly major refactor addresses several feature requests around lifecycle hooks, and the ability to skip steps that standard-version performs.
There are now the events `bump`, `changelog`, `commit, and `tag`, each of which has `pre` and `post` lifecycle hooks, e.g., `prebump`, `postbump`, `precommit`, ...
fixes #157
I've branched from https://github.com/conventional-changelog/standard-version/pull/187 which should be landed first (so this commit looks bigger than it actually is).
CC: @lancecaraccioli, @denouche,
> feat: add support for skipping lifecycle steps, polish lifecycle work

- lib/lifecycles/tag.js
- test.js
The --tag argument to npm publish allows you to publish a prerelease without the prerelease assuming
the 'latest' tag and causing users to download the prerelease by default. Instead, we recommend
`--tag prerelease` by default when `--prerelease` is set in the `standard-version` call, so to
install a prerelease version of the module, users will install `module@foo` or specify the exact
version of the prerelease version.
Fixes #183 
Supersedes #189
> fix: Recommend --tag prerelease for npm publish of prereleases

- command.js
Even though the defaults for both `skip` and `scripts` were empty
objects, the code was referencing the default value for `scripts` in
both places, which could lead to a bug in the future if the default for
either changed at some point in the future.
> fix: use the `skip` default value for skip cli arg

- lib/lifecycles/changelog.js
Use tagPrefix arg if passed also in conventional-changelog
If we won't to do it, the last commit won't find if we use custom tagPrefix
> Use tagPrefix in conventional-changelog

- index.js
- lib/lifecycles/bump.js
- test.js
Hi there,
I've added support for updating a `manifest.json` file, which is used in Google Chrome extensions. 
There's potential in standard-release to be used for software packages that are not node.js related or don't use npm. And I think this is a good start towards that.
Thank you for this tool btw, it's helped me a lot!
> feat: manifest.json support

- lib/lifecycles/tag.js
Tried this package out for the first time and wanted to undo what it had done.
When I tried to remove the tag, I assumed the output "tagging release 0.0.1" was the exact name of the tag, but it was `v0.0.1`.
This changes it so the output is representing the actual name of the tag, and not just the version.
> Show full tag name in checkpoint

- README.md
- lib/lifecycles/bump.js
- test.js
It took me a while to get around to it, but here's an implementation of a pre-everything script hook that won't affect behavior further into the process.
> feat: add prerelease lifecycle script hook (closes #217)

- lib/lifecycles/tag.js
- test.js
Hi,
This change adds the correct advise to push the same named tag to npm, too.
So that `npm run release -- --prerelease alpha` advises to push to the alpha tag on npm
> Releasing named prerelease advises to push same tag-name

- package.json
fixes #175
exports.prerelease was added in 5.2.0, see:
https://github.com/npm/node-semver/commit/3cc5a94c15f5874b7c12f7cc5cf03f8f07b476ba
> fix semver dep version

- README.md
- command.js
- defaults.json
- index.js
- lib/latest-semver-tag.js
- lib/lifecycles/bump.js
- test.js
_I'm working on some mad science with GitHub Actions, as part of this I'm working on making standard-version less tied to JavaScript._
This pull request makes it so that version will now be based on the git-history, if no supported meta-information file is found (package.json, composer.json, etc).
I've also updated the language slightly in the README to tie things less to npm.
BREAKING CHANGE: if no package.json, bower.json, etc., is found, we now fallback to git tags
CC: @TilmannBach
> feat: fallback to tags if no meta-information file found

- README.md
> docs(readme): :memo: update code usage

- package.json
`dependencies` in package.json doesn't list some direct dependencies of this project (now it works only by chance, that deep level dependencies are installed top level)
(as a side note: such errors could be avoided by relying on [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) eslint rule)
> Register missing dependencies

- index.js
- lib/lifecycles/bump.js
- package.json
- test.js
This PR implements a feature (or maybe it's a fix?) to get `standard-version` to preserve the indentation and 
line feed of `package.json` instead of overriding the user's preferred format with 2 space indentation. (See #43)
`detect-indent` and `detect-newline` are used to figure out the current indentation of `package.json`. This is done in an identical way to how `npm` handles writing changes to `package.json`.
Notable internal change:
1. `package.json` is no longer loaded with `require()`. While it should be functionally identical, in order to detect the formatting, the file to be read in as plain text. This caused certain tests to fail since the require cache wasn't updated during the bump, resulting in additional places where the cache needed to be deleted between invocations of the …
> feat: preserve formatting when writing to package.json

- command.js
- defaults.json
- index.js
- lib/lifecycles/bump.js
- lib/lifecycles/changelog.js
Path option will be passed down to:
1. `conventional-recommended-bump` to produce correct version
2. `conventional-changelog` to produce correct changelog
Specifically it will be used by `git-raw-commits` package.
> feat: cli application accept path option

- lib/lifecycles/changelog.js
This pull request updates the search pattern for finding changelog sections to account for section headers that don't have anchors (in addition to section headers that _do_ have anchors).
This change is needed because Conventional Changelog [removed anchors from changelog templates](https://github.com/conventional-changelog/conventional-changelog/commit/346f24f0f8d92b64ed62658796d1876a52ec3ab3). That change has not been included in the conventional-changelog dependency for `standard-version` yet, but will need to be addressed before it can be. Additionally, manually edited changelogs may not include these anchors, which means that this change will make it easier to adopt `standard-version` into existing projects.
> fix: update search pattern for finding changelog sections

- lib/lifecycles/commit.js
- test.js
The commit message now shows that all staged files are committed too.
> fix: update commit msg for when using commitAll

- .eslintrc
- command.js
- index.js
- lib/lifecycles/bump.js
- lib/lifecycles/changelog.js
- lib/lifecycles/commit.js
- lib/lifecycles/tag.js
- lib/run-lifecycle-hook.js
- lib/run-lifecycle-script.js
- package.json
- test.js
- No longer uses `standard` directly, instead uses the [recommmend manual configuration](https://github.com/standard/eslint-config-standard) to allow for the addition of the [`no-var`](https://eslint.org/docs/rules/no-var) eslint rule.
- Uses `eslint . --fix` after the configuration update to swap `var` usage to `let`
see #276
> chore: Updates `var` usage to `let`

- CHANGELOG.md
- README.md
- command.js
- defaults.json
- lib/lifecycles/bump.js
- lib/lifecycles/changelog.js
- lib/preset-loader.js
- package.json
- test.js
Int his PR we introduce the conventionalcommits preset, here's why this is cool:
* the conventionalcommits preset is based directly on https://github.com/conventional-commits/conventionalcommits.org/pull/141, allowing us to better handle the slight deviations from angular's convention, e.g., the recent introduction of a `!` character for breaking changes.
* the conventionalcommits preset is highly configurable based on the [specification described here](https://github.com/conventional-changelog/conventional-changelog-config-spec).
* this will allow `standard-version` to better support options other than GitHub in a well documented, standardized way.
BREAKING CHANGE: switches default preset to conventionalcommits
----
This change is currently blocked by:
* …
> feats: adds new configurable conventionalcommits preset

- lib/lifecycles/changelog.js
- test.js
> fix: prevent duplicate headers from being added (#305)

- test.js
My ~/.gitconfig has `commit.gpgSign=true`, earlier I ran the test when
my gpg-agent was not active and got prompted for my gpg password.  This
adds config to the temporary test repositories to avoid automatic
signing of commits.
> chore: Disable gpg signing in temporary test repositories.

- README.md
The documentation only describes how to apply custom tag prefixes and it does not mention the default tag prefix (`v`) or how to apply no prefix at all.
This PR adds this missing information to the README (based on my own findings, please correct me if I'm wrong).
> docs(readme): describe how to apply no tag prefix at all

- lib/lifecycles/tag.js
git push guideline message at the end is shown as `git push --follow-tags origin master` though the change log is generated in a different branch. People not only use `master` branch but also `develop` or different branch. This fix will add the current branch name instead of master to the message.
closes #249
> fix: git push guideline message with right branch name

- .travis.yml
- test.js
This was caused by tests in #320 using `var` and being merged into the trunk (as-is) just before the new eslint rules (#321)
---
This should fix the build errors we're seeing in some of the latest PRs.
> test: use const based on new eslint rules

- lib/lifecycles/bump.js
- test.js
fixes #308 
BREAKING CHANGE: we now bump the minor rather than major if version < 1.0.0
> feat!: bump minor rather than major, if release is < 1.0.0

- lib/lifecycles/bump.js
- lib/lifecycles/commit.js
- lib/lifecycles/tag.js
- test.js
`standard-version@5.0.0` introduced git tag fallback, but it is still suggesting `npm publish` even if `package.json` was not updated.
Added a check so it doesn't. Could later be generalized for bower and composer, etc...?
Did a small refactor in `bump.js` so that the check would be simpler.
> fix: stop suggesting npm publish if package.json was not updated

- lib/lifecycles/commit.js
- test.js
If you skip changelog generation standard-version fails to process the remaining checkpoints. This PR provides a fix.
+ Prevent `CHANGELOG.md` or any given `infile` from being added to git when skipped.
+ Prevent `CHANGELOG.md` or any given `infile` from being added to the output when skipped.
Given this config:
```
"standard-version": {
"skip": {
"changelog": false,
"tag": true
}
},
```
Before
```
✔ bumping version in package.json from 1.0.0 to 1.1.0
✔ committing package.json and CHANGELOG.md
fatal: pathspec 'CHANGELOG.md' did not match any files
Command failed: git add package.json CHANGELOG.md
fatal: pathspec 'CHANGELOG.md' did not match any files
```
After 
```
✔ bumping version in package.json from 1.0.0 to 1.1.0
✔ committing package.json
```
Could not find any tests so I made the …
> fix(commit): don't try to process or to add changelog if it's skipped

- command.js
Changed the filename based on this section:
https://github.com/conventional-changelog/standard-version#configuration
> fix: update config file name in command based on README.md

- command.js
Previously `--help` would print both "angular" and "conventionalcommits" as defaults for `--preset`, which was confusing.
`$ standard-version --help`
Before:
```
--preset             Commit message guideline preset (default: angular)
[string] [default:"conventionalcommits"]
```
After:
```
--preset             Commit message guideline preset  [string] [default: "conventionalcommits"]
```
> fix(cli): Display only one, correct default for --preset flag

- package.json
- 6 support was dropped in May (671842853b9fa62ecda126bf5e1fbe7aa60a5d1f), 4 and 5 were dropped in November 2018 (1d466275518ae2649758b9e0e9b3c848734f534f)
We should be able to close out (#286) once this is merged. It's the only changed [that was mentioned](https://github.com/conventional-changelog/standard-version/issues/286#issuecomment-446550907) that hasn't made it into a tagged version.
> fix: Updates package.json to _actual_ supported (tested) NodeJS versions.

- test.js
This will give us coverage for #371.
> test: adds tests for .versionrc.json usage

- README.md
I had no idea what to put in the `.versionrc` until i stumbled upon the spec. A sample for how to do it in the `package.json` would be a great resource also but I don't know how to do that from reading the docs.
It is still unclear to me if it is only cli options are available or if the options in link I provided also work.
> docs: add link to configuration spec

- README.md
To help simpletons such as myself understand how yargs work (see #373)
> docs(cli): note about yargs dot notation in lieu of package.json

- package.json
- test.js
- This will bump the transitive dependencies found in conventional-changelog which should ensure we're keeping in-sync with the features and fixes being applied to presets.
- This *did* require a change to a test case's expected output (-2 new-lines)... I don't think this needs to be seen as breaking and my assumption is it was just caused by some tweaks to templates in the conventional-changelog-conventionalcommits preset.
> deps: bumps conventional-changelog to 3.1.9

- lib/lifecycles/bump.js
The `prefixTag` is never transmitted to `conventionalRecommendedBump` parameters.
In my case, I have a monorepo with several prefixed tags and `standard-version` would always bump to major because of using wrong "from" tag.
> fix(bump): transmit tag prefix argument to conventionalRecommendedBump

- README.md
- I just removed the reference to the Angular format for now... I'm not entirely sure the comparison/evaluation to `semantic-release` is still correct, but that seems like something we can evaluate _later_. 
closes #406
> docs(README): Removes refrences to Angular convention.

- package.json
- This is expected to resolve #410 based on updates in the conventional-commits preset.
> chore(deps,conventional-changelog): Bumps conventional-changelog to 3.1.10

- README.md
- command.js
- lib/configuration.js
- test.js
- Updates the configuration retrieval to support Javascript (`.js`) configurations.
- Javascript configurations MUST export a configuration object _or_ a function (returning a configuration object) as the default export.
- Adds details around `.versionrc.js` to README.
closes #371
>  feat(configuration): .versionrc.js files are now supported

- test.js
- This was an attempt to reproduce conventional-changelog/conventional-changelog-config-spec#34, but it's something we didn't have explicit coverage for.
> test: Adds a case for loading a configuration (issueUrlFormat) from package.json.

- defaults.js
- lib/preset-loader.js
- package.json
In order to support Yarn 2/PnP, `conventional-changelog-conventionalcommits` must be declared in package.json and referenced using `require.resolve`.
Requires https://github.com/conventional-changelog/conventional-changelog/pull/530
> fix: enforce require.resolve for the default preset

- README.md
When I updated the package to version `7.1.0` and added to config 
```
"bumpFiles": [
{
"file": "path/to/file.jsom",
"type": "json"
}
],
```
I get error `Path must be a string. Received undefined`. But when I changed `file` key to `filename`, then script is work
> doc: bumpFiles key for file path is not valid

- defaults.js
closes #394
[Composer docs](https://getcomposer.org/doc/04-schema.md#version) states that version in composer.json is
> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.
> No need to bumb version in composer.lock and composer.json

- README.md
I've spend at least an hour to figure out why my configuration files were always ignored. After debugging the source of my `node_modules/standard-version/*` it turns out I had `7.0.1` installed which apparently does not have the feature of `bumpFiles` or `packageFiles`.
I don't understand why `7.0.1` and not `7.1.0` got installed. I used `yarn add --dev standard-version`.
close #504
close #271
> docs(configuration): Fix typo & required versions

- package.json
- test.js
The mock-git tests now exhibit a variety of odd behaviors on Windows:
* an error is captured and output regarding line endings.
* the commands ultimately passed to the `git` bin are in a different format (this is probably related to the switch to [`execFile`](https://github.com/conventional-changelog/standard-version/security/advisories/GHSA-7xcx-6wjh-7xp2).
tldr; let's turn off these tests on Windows for now.
> test(windows): skip mock-git tests for Windows

- .github/ISSUE_TEMPLATE/ask-a-question.md
- .github/ISSUE_TEMPLATE/bug-report.md
An attempt to standardize our issue backlog... since it's easy for these issues to become stale it would be helpful to ensure/ask folks to explicitly list some information about their environment/versions to tighten the feedback loop a little bit.
> chore: Adds basic issue templates

- lib/lifecycles/commit.js
- lib/lifecycles/tag.js
- test.js
Remove unwanted quotes from commit message and tag name.
With current version:
Fix #620
Fix #621
> fix: don't enclose commit message and tag name in quotes

- README.md
- lib/updaters/index.js
- test/core.spec.js
This adds support for defining the `updater` directly in a JS config file, rather than requiring it to be passed in as a path to be `require`d.
Fixes #631
> feat: support custom updater as object as well as path

- index.js
- lib/lifecycles/bump.js
- lib/lifecycles/changelog.js
- lib/lifecycles/commit.js
- lib/lifecycles/tag.js
- lib/run-exec.js
- lib/run-execFile.js
The current code style of this library is promise-based, using long chains of then/catch blocks. This PR replaces those in favour of async/await, which is well supported in Node.js 10, the minimum required by `standard-version`.
The logic of the code does not change here at all, but this allows for the code to have significantly less boilerplate syntax. Data flow is also simplified a little bit.
> refactor: use async/await syntax to simplify source files

- README.md
- Updates badge based on the removal of Travis (#583)
> docs(README): Updates the CI status badge to source from GitHub workflows.

- README.md
The Readme defines `bumpFiles` as:
```
User-defined files where versions should be "bumped", but not explicitly read from.	- **`bumpFiles`** – User-defined files where versions should be "bumped", but not explicitly read from.
- Examples: `package-lock.json`, `npm-shrinkwrap.json`
```
But the `Retrieval` point mentioned reading from`bumpFile` rather than `packageFiles`. 
Thanks.
> docs: changed bumpFiles to packageFiles for retrieval point 

- .github/workflows/ci.yaml
- README.md
- package.json
We dropped pushing [updates to Coveralls](https://coveralls.io/github/conventional-changelog/standard-version) from CI when we moved to GitHub actions. It looks like _most_ of the org is using Codecov as we no longer have Coveralls configured. 
- Removes coveralls integration.
- Updates GitHub actions to include CodeCov step.
- Moves OS to strategy matrix – we're now testing across multiple versions of Windows.
- Related dependency bumps.
---
> chore(deps, ci): Updates nyc and moves to Codecov

- lib/updaters/types/json.js
NPM v7 introduces a new package-lock.json version, which now stores the project's version in two places: `lock.version` and `lock.packages[''].version`. This updates `writeVersion` to also bump the latter if present in the file.
Please let me know if you have any further questions.
> fix(updater): npm7 package lock's inner version not being updated

- README.md
Unfortunately, I don't have time to continue maintaining standard-version, partially because the tool [release-please](https://github.com/googleapis/release-please) meets all my needs.
If anyone is interested in forking this repository, and the fork gets some traction, I will happy link to it from this repository (_this is where yargs came from, it was a fork of optimist_).
> feat(deprecated): add deprecation message

- README.md
As discussed on #919, this PR edits the deprecation notice to include a link to the fork that I've been maintaining for the past 6 months.
> docs: Add link to commit-and-tag-version as per #919
